baseURL: https://ansonprojects.com
languageCode: en-us
build:
  writeStats: true
params:
  # title: aafu theme
  author: Anson Olive
  description: My Portfolio
  # copyright:
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">
  profile:
    name: "Anson Olive"
    tagline: Nuclear Engineer
    location: "College Station, Texas"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/ansonolive/"
        title: LinkedIn
      #- icon: fab fa-stack-overflow
      #  url: "#"
      #  title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/AnsOlive"
        title: GitHub
      #- icon: fab fa-twitter
      #  url: "#"
      #  title: Twitter
      #- icon: fab fa-orcid
      #  url: "#"
      #  title: Orcid
      #- icon: ai ai-google-scholar
      #  url: "#"
      #  title: Google Scholar
      #- icon: fab fa-researchgate
      #  url: "#"
      #  title: ResearchGate
  showInAccordion:
    - item: aboutme
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: Hello! My name is Anson Olive and I am a nuclear engineer interested in fusion, programming, and experimentation. Please browse my projects and feel free to reach out to me. Thank you for stopping by!
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Fusion Energy Researcher
        dates: August 2023 - Present
        company: Texas A&M University Department of Nuclear Engineering
        details: |1-
          - Developed OpenMC Monte Carlo simulations for tritium production in a lithium blanket of the Commonwealth Alcator C-mod reactor.
          - Explored scientific documentation to further applications of fusion reactors in industry.
          - Collaborated on neutronics and heat transfer computations for the HYLIFE fusion reactor design.
      - position: Microdosimetry Researcher
        dates: October 2023 - Present
        company: Texas A&M University
        details: |1-
          - Improved microdosimeter designs using SolidWorks to enhance strength and reduce microphonic noise.
          - Published research on a hexagonal microdosimeter design at the 2024 INMM conference.
      - position: Project Engineer
        dates: May 2024 - August 2024
        company: Fluor
        details: |1-
          - Facilitated cross-disciplinary communication for a $12 billion project to retrofit Savannah River National Laboratory facilities.
          - Adapted project designs to evolving customer requirements.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Bachelor of Science in Nuclear Engineering, Minor in Mathematics
        college: Texas A&M University Engineering Honors
        dates: August 2022 - December 2025
        gpa: 3.533 GPA
  #activities:
  #  title: Activities & Leadership
  #  icon: fas fa-users
  #  list:
  #    - title: Fusion Club Officer
  #      role: Treasurer
  #      dates: November 2024 - Present
  #    - title: Running Club
  #      role: Race Coordinator
  #      dates: August 2023 - Present
  #    - title: T.U.R.T.L.E Robotics Club
  #      role: System Designer
  #      dates: January 2023 - May 2024
  publication:
    title: Publications
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        authors: "F Last, F Second, P secondary"
        date: "2018"
        journal: "Journal of Field 52 (16), 9033-9044"
        url: "#"
        type: Journal Articles
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: My Portfolio Website
        url: "https://ansonprojects.netlify.app/"
        description: Description of the project
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "OpenMC, MCNP, MOOSE"
        skillrating: 95
      - skill: "Python, C++, Linux"
        skillrating: 90
      - skill: "SolidWorks, 3D Printing, Git"
        skillrating: 85
      - skill: "Project Management, Oratory, Scientific Research"
        skillrating: 80
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Running
      - hobby: Cooking & Baking
        list:
      - title: Fusion Club Officer
        role: Treasurer
        dates: November 2024 - Present
      - title: Running Club
        role: Race Coordinator
        dates: August 2023 - Present
      - title: T.U.R.T.L.E Robotics Club
        role: System Designer
        dates: January 2023 - May 2024